# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=60, verbose_name='关键字')),
            ],
        ),
        migrations.CreateModel(
            name='KeyToQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField(default=0, verbose_name='查询次数')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k2qa', to='qa_index.KeyItem')),
            ],
        ),
        migrations.CreateModel(
            name='QAItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='题目')),
                ('answer', models.TextField(verbose_name='答案')),
            ],
        ),
        migrations.AddField(
            model_name='keytoqa',
            name='qa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k2qa', to='qa_index.QAItem'),
        ),
    ]
