# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaitem',
            name='desc',
            field=models.TextField(default='描述', verbose_name='描述'),
        ),
    ]
